// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CorePhotoAlbum.Models
{
    public partial class Comments
    {
        public int CommentId { get; set; }
        public int PhotoId { get; set; }
        public string UserName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }

        public virtual Photos Photo { get; set; }
    }
}