// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CorePhotoAlbum.Models
{
    public partial class PhotosharingdbContext : DbContext
    {
        public PhotosharingdbContext()
        {
        }

        public PhotosharingdbContext(DbContextOptions<PhotosharingdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Comments>(entity =>
            {
                entity.HasKey(e => e.CommentId)
                    .HasName("PK_dbo.Comments");

                entity.HasIndex(e => e.PhotoId)
                    .HasName("IX_PhotoID");

                entity.Property(e => e.CommentId).HasColumnName("CommentID");

                entity.Property(e => e.PhotoId).HasColumnName("PhotoID");

                entity.HasOne(d => d.Photo)
                    .WithMany(p => p.Comments)
                    .HasForeignKey(d => d.PhotoId)
                    .HasConstraintName("FK_dbo.Comments_dbo.Photos_PhotoID");
            });

            modelBuilder.Entity<Photos>(entity =>
            {
                entity.HasKey(e => e.PhotoId)
                    .HasName("PK_dbo.Photos");

                entity.Property(e => e.PhotoId).HasColumnName("PhotoID");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Title).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}