// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CorePhotoAlbum.Models
{
    public partial class Photos
    {
        public Photos()
        {
            Comments = new HashSet<Comments>();
        }

        public int PhotoId { get; set; }
        public string Title { get; set; }
        public byte[] PhotoFile { get; set; }
        public string ImageMimeType { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UserName { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<Comments> Comments { get; set; }
    }
}